### PR TITLE
fix typing on search/match/findall/sub/...

### PR DESCRIPTION
**Pull request by trim21**
you can run `mypy tests` and `python tests/api/__init__.py` to verify typing are both valid at runtime and typing level.

this should suppress https://github.com/ddn0/google-re2-stubs/pull/4 , patch are included in this PR.

> Looks like I misunderstood how re2 handle inputs and you misunderstood how `AnyStr` works here.
>
> I find that methods on `re2.compile(str(...)).match/findall/sub/...` can handle bytes input, so it dones't need to be `AnyStr`. For python stdlib `re`, pattern and string must have same type but it's not true for re2, re2 can run bytes pattren on string or string pattern on bytes, which means `re.findall("1", b"0 1 2")` doesn't work but `re2.findall("1", b"0 1 2")` works.
>
> And `AnyStr` is a `TypeVar` and in `class _Regexp(Generic[AnyStr])` it will be narrowed base on the type of `re2.compile()`, but not narrowed at function/method level by the input string.
>
> This make most methods in `_Regexp` have wrong typing, I'll send a seprated PR to fix them later

### CODE REVIEW

**Comment by trim21** [comment]
A good thing on Python typing is that even original package doesn't have typing, you can still use typing stub.

If you do not want to maintain this package I can keep maintaining it. re2 looks pretty stable so I guess we won't need to change this package very much.

I know nothing about gerrit or bazel, it will take me lots of time to 
learn them first to submit a PR to re2 main package, it would be much easier for me to just maintain a type stubs.

**Comment by ddn0** [comment]
Sorry for the delay, I'll review this PR soon.

**Comment by ddn0** [comment]
Thanks!

I learned a lot more about constrained types.

I just had some style issues. And to speed up convergence, I just applied my suggestions to your PR.

Let me know if you have any objections by Tuesday end ([anywhere on earth](https://time.is/Anywhere_on_Earth) "timezone"); otherwise, I'll merge the PR as it is and prepare a new PyPI release with these changes.

**Comment by trim21** [comment]
LGTM.

sadly we can't export `Match` and `Regex`

**Comment by trim21** [comment]
new pypi release?

**Comment by ddn0** [comment]
Done!

**Pull request merged**
